### ISSUE TITLE
[eksctl]: error creating cluster in us-east-1

### ISSUE THREAD

**Issue by shabbskagalwala** [ACloudGuru-Resources/Course_Practical_Guide_EKS#31]
A constant issue I keep running into when creating the cluster in `us-east-1` is 
```
2022-03-26 00:51:56 [✖]  AWS::EKS::Cluster/ControlPlane: CREATE_FAILED – "Resource handler returned message: \"Cannot create cluster 'eks-bookstore-project' because us-east-1e, the targeted availability zone, does not currently have sufficient capacity to support the cluster. Retry and choose from these availability zones: us-east-1a, us-east-1b, us-east-1c, us-east-1d, us-east-1f (Service: Eks, Status Code: 400, Request ID: 2d525fed-1b2e-460c-aa8a-6c747ffad5ac)\" (RequestToken: 958b48c7-6bc6-497c-8306-655de5a8b8bf, HandlerErrorCode: InvalidRequest)"
```

A good workaround would be to update the `cluster.yaml` files to include `availabilityZones` as a key as mentioned in the `eksctl` documentation and restrict the AZ's to only 3 or possibly 4 as per the needs of the course :)

My sample `cluster.yaml` file looks like this
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-bookstore-project
  region: us-east-1
  version: "1.20"

availabilityZones:
  - us-east-1a
  - us-east-1b
  - us-east-1c

vpc:
  cidr: 10.0.0.0/16

nodeGroups:
  - name: eks-node-group
    instanceType: t3.micro
    desiredCapacity: 3
    privateNetworking: true
```

I can create a PR for this if I have the 👍 from the course instructor.
